version: '2'

services:

  wordpress:
    image: wordpress
    depends_on:
      - "mysql"
    links:
      - mysql:mysql
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_PASSWORD=example
    volumes:
      - ./wp:/var/www/html

  mysql:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example
    volumes:
      - ./wpdb:/var/lib/mysql
